In [1]:
import os

folders = [
    "data/raw",
    "data/cleaned",
    "data/processed",
    "notebooks",
    "sql",
    "powerbi",
    "tableau",
    "excel",
    "screenshots",
    "reports",
    "docs"
]

for folder in folders:
    os.makedirs(folder, exist_ok=True)

print("Project folders created successfully!")

Project folders created successfully!

In [2]:
import pandas as pd
import numpy as np

In [5]:
df = pd.read_csv(r"C:\Users\asus\OneDrive\Documents\Youtube_data_analysis\data\raw\youtube.raw.csv")

In [6]:
df.head()

,title,channelName,viewCount,likes,date,duration,type,url,commentsCount
0,Every Machine Learning Model Explained in 15 m...,Brain Station Advanced,268049.0,11000.0,2026-03-02T12:30:13.000Z,00:16:03,video,https://www.youtube.com/watch?v=63Kr3HFECHM,89.0
1,Machine Learning for Everybody – Full Course,freeCodeCamp.org,10172516.0,109000.0,2022-09-26T16:00:28.000Z,03:53:53,video,https://www.youtube.com/watch?v=i_LwzRVP7bg,2306.0
2,11. Introduction to Machine Learning,MIT OpenCourseWare,1815363.0,26000.0,2017-05-19T14:22:40.000Z,00:51:30,video,https://www.youtube.com/watch?v=h0e2HAPTGF4,514.0
3,Machine Learning | What Is Machine Learning? |...,Simplilearn,5486835.0,68000.0,2018-09-19T14:57:02.000Z,00:07:52,video,https://www.youtube.com/watch?v=ukzFI9rgwfU,2227.0
4,Machine Learning Explained Simply (In 12 Minutes),The Gradient Descent,115149.0,5000.0,2026-01-07T02:00:10.000Z,00:12:24,video,https://www.youtube.com/watch?v=Au1OxVSyGas,120.0

In [7]:
df.shape

(300, 9)

In [8]:
df.columns

Index(['title', 'channelName', 'viewCount', 'likes', 'date', 'duration',
       'type', 'url', 'commentsCount'],
      dtype='str')

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   title          298 non-null    str
 1   channelName    298 non-null    str
 2   viewCount      298 non-null    float64
 3   likes          298 non-null    float64
 4   date           298 non-null    str
 5   duration       298 non-null    str
 6   type           298 non-null    str
 7   url            300 non-null    str
 8   commentsCount  298 non-null    float64
dtypes: float64(3), str(6)
memory usage: 67.3 KB

In [10]:
df.describe()

          viewCount          likes  commentsCount
count  2.980000e+02     298.000000     298.000000
mean   2.965490e+06   33580.268456    1708.312081
std    2.567224e+07   73300.500360    4304.299180
min    3.170000e+02       0.000000       0.000000
25%    1.121390e+05    2700.000000      99.000000
50%    4.185115e+05    9850.000000     378.000000
75%    1.618555e+06   33750.000000    1412.250000
max    4.415352e+08  663000.000000   39560.000000

In [12]:
df.isnull().sum()

title            2
channelName      2
viewCount        2
likes            2
date             2
duration         2
type             2
url              0
commentsCount    2
dtype: int64

In [13]:
df[df.isnull().any(axis=1)]

,title,channelName,viewCount,likes,date,duration,type,url,commentsCount
164,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://www.youtube.com/watch?v=Du-GWB4g7GY,NaN
228,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://www.youtube.com/watch?v=KzVS25P3F1k,NaN

In [14]:
df = df.dropna()

In [15]:
df.isnull().sum()

title            0
channelName      0
viewCount        0
likes            0
date             0
duration         0
type             0
url              0
commentsCount    0
dtype: int64

In [16]:
df.duplicated().sum()

np.int64(0)

In [17]:
df.dtypes

title                str
channelName          str
viewCount        float64
likes            float64
date                 str
duration             str
type                 str
url                  str
commentsCount    float64
dtype: object

In [20]:
df.to_csv("youtube_cleaned.csv", index=False)
print(" saved cleaned  file")

 saved cleaned  file

In [21]:
df_clean = df.copy()

In [22]:
df_clean.dtypes

title                str
channelName          str
viewCount        float64
likes            float64
date                 str
duration             str
type                 str
url                  str
commentsCount    float64
dtype: object

In [26]:
numeric_cols = ['viewCount', 'likes', 'commentsCount']

for col in numeric_cols:
    df_clean[col] = pd.to_numeric(df_clean[col], errors='coerce')

In [27]:
df_clean.dtypes

title                            str
channelName                      str
viewCount                    float64
likes                        float64
date             datetime64[us, UTC]
duration                         str
type                             str
url                              str
commentsCount                float64
dtype: object

In [25]:
df_clean['date'] = pd.to_datetime(df_clean['date'], errors='coerce')

In [28]:
df_clean['date'].head()

0   2026-03-02 12:30:13+00:00
1   2022-09-26 16:00:28+00:00
2   2017-05-19 14:22:40+00:00
3   2018-09-19 14:57:02+00:00
4   2026-01-07 02:00:10+00:00
Name: date, dtype: datetime64[us, UTC]

In [29]:
df_clean.isnull().sum()

title            0
channelName      0
viewCount        0
likes            0
date             0
duration         0
type             0
url              0
commentsCount    0
dtype: int64

In [30]:
df_clean['url'].duplicated().sum()

np.int64(0)

In [31]:
df_clean['upload_year'] = df_clean['date'].dt.year

In [32]:
df_clean['upload_month'] = df_clean['date'].dt.month_name()

In [33]:
df_clean['upload_day'] = df_clean['date'].dt.day_name()

In [34]:
df_clean['upload_hour'] = df_clean['date'].dt.hour

In [35]:
df_clean['engagement_rate'] = (
    (df_clean['likes'] + df_clean['commentsCount'])
    / df_clean['viewCount']
) * 100

In [36]:
df_clean['like_ratio'] = (
    df_clean['likes']
    / df_clean['viewCount']
) * 100

In [37]:
df_clean['comment_ratio'] = (
    df_clean['commentsCount']
    / df_clean['viewCount']
) * 100

In [40]:
df_clean['popularity_score'] = (
      df_clean['viewCount'] * 0.5
    + df_clean['likes'] * 0.3
    + df_clean['commentsCount'] * 0.2
)

In [41]:
df_clean.head()

,title,channelName,viewCount,likes,date,duration,type,url,commentsCount,upload_year,upload_month,upload_day,upload_hour,engagement_rate,like_ratio,comment_ratio,popularity_score
0,Every Machine Learning Model Explained in 15 m...,Brain Station Advanced,268049.0,11000.0,2026-03-02 12:30:13+00:00,00:16:03,video,https://www.youtube.com/watch?v=63Kr3HFECHM,89.0,2026,March,Monday,12,4.136930,4.103727,0.033203,137342.3
1,Machine Learning for Everybody – Full Course,freeCodeCamp.org,10172516.0,109000.0,2022-09-26 16:00:28+00:00,03:53:53,video,https://www.youtube.com/watch?v=i_LwzRVP7bg,2306.0,2022,September,Monday,16,1.094184,1.071515,0.022669,5119419.2
2,11. Introduction to Machine Learning,MIT OpenCourseWare,1815363.0,26000.0,2017-05-19 14:22:40+00:00,00:51:30,video,https://www.youtube.com/watch?v=h0e2HAPTGF4,514.0,2017,May,Friday,14,1.460534,1.432220,0.028314,915584.3
3,Machine Learning | What Is Machine Learning? |...,Simplilearn,5486835.0,68000.0,2018-09-19 14:57:02+00:00,00:07:52,video,https://www.youtube.com/watch?v=ukzFI9rgwfU,2227.0,2018,September,Wednesday,14,1.279918,1.239330,0.040588,2764262.9
4,Machine Learning Explained Simply (In 12 Minutes),The Gradient Descent,115149.0,5000.0,2026-01-07 02:00:10+00:00,00:12:24,video,https://www.youtube.com/watch?v=Au1OxVSyGas,120.0,2026,January,Wednesday,2,4.446413,4.342200,0.104213,59098.5

In [42]:
df_clean.info()

<class 'pandas.DataFrame'>
Index: 298 entries, 0 to 299
Data columns (total 17 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   title             298 non-null    str
 1   channelName       298 non-null    str
 2   viewCount         298 non-null    float64
 3   likes             298 non-null    float64
 4   date              298 non-null    datetime64[us, UTC]
 5   duration          298 non-null    str
 6   type              298 non-null    str
 7   url               298 non-null    str
 8   commentsCount     298 non-null    float64
 9   upload_year       298 non-null    int32
 10  upload_month      298 non-null    str
 11  upload_day        298 non-null    str
 12  upload_hour       298 non-null    int32
 13  engagement_rate   298 non-null    float64
 14  like_ratio        298 non-null    float64
 15  comment_ratio     298 non-null    float64
 16  popularity_score  298 non-null    float64
dtypes: datetime64[us, UTC](1), float64(7), int32(2), str(7)
memory usage: 82.3 KB

In [43]:
df_clean.to_csv(
    "youtube_final.csv",
    index=False
)